# Generated by Django 5.0.14 on 2026-07-08 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=128)),
                ('industry_type', models.CharField(max_length=150)),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('coordinator_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('department', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Coordinator',
                'verbose_name_plural': 'Coordinators',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolAdmin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'School Admin',
                'verbose_name_plural': 'School Admins',
                'ordering': ['admin_id'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('contact_number', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=128)),
                ('course', models.CharField(max_length=150)),
                ('department', models.CharField(max_length=150)),
                ('year_level', models.PositiveSmallIntegerField()),
                ('section', models.CharField(max_length=20)),
                ('required_hours', models.PositiveIntegerField(help_text='Total OJT hours required for this student')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='OJTPlacement',
            fields=[
                ('placement_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('required_hours', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Terminated', 'Terminated')], default='Pending', max_length=20)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='placement.company')),
                ('coordinator', models.ForeignKey(db_column='coordinator_id', on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='placement.coordinator')),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='placement.student')),
            ],
            options={
                'verbose_name': 'OJT Placement',
                'verbose_name_plural': 'OJT Placements',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('log_date', models.DateField()),
                ('time_in', models.TimeField(blank=True, null=True)),
                ('time_out', models.TimeField(blank=True, null=True)),
                ('rendered_hours', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late'), ('Excused', 'Excused')], default='Present', max_length=20)),
                ('remarks', models.CharField(blank=True, default='', max_length=255)),
                ('placement', models.ForeignKey(db_column='placement_id', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='placement.ojtplacement')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['-log_date'],
            },
        ),
    ]
