# Generated by Django 5.0.14 on 2026-07-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooladmin',
            name='admin_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
